### ISSUE TITLE
Latest Pytest release (3.3.1) breaks pytest-pudb

### ISSUE THREAD

**Issue by mandx** [wronglink/pytest-pudb#12]
Simply because of this method renaming in Pytest's CaptureManager plugin: `suspendcapture` -> `suspend_global_capture`. Using the new name works (so far).

Apparently the fix could also make this work with pre-3.3.1 version of Pytest. (try use the new name, otherwise use the old name).

**Comment by spacelis** [comment]
I hit this too. @mandx is right and I created PR #13 for it.
